sudo: false
language: ruby

rvm:
- ruby-head
- 2.4.2
- 2.3.5
- 2.2.8
- 2.1.10

env:
  global:
  - PYCALL_DEBUG_FIND_LIBPYTHON=1
  matrix:
  - PYTHON=python PYTHON_VERSION=2
  - PYTHON=python3 PYTHON_VERSION=3 LIBPYTHON=wrong_value
  - PYTHON_VERSION=3 LIBPYTHON=/opt/python/3.5.3/lib/libpython3.5m.so
  - ANACONDA=1 PYTHON_VERSION=2
  - ANACONDA=1 PYTHON_VERSION=3

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
  - os: osx
    osx_image: xcode9
    compiler: clang

addons:
  apt:
    packages:
    - python3
    - python3-dev
    - python3-all
    - python3-all-dev

before_install:
- gem update --system
- gem update bundler

install:
- source ci/python_install.sh
- bundle install

before_script:
- bundle exec rake clobber compile
- echo === python investigator.py ===
- python lib/pycall/python/investigator.py
- python3 lib/pycall/python/investigator.py
