sudo: false
language: ruby

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head

addons:
  apt:
    packages:
      - python3
      - python3-dev
      - python3-all

before_install:
  - gem update --system
  - gem update bundler
