sudo: false
language: ruby

rvm:
  - ruby-head
  - 2.4.0
  - 2.3.1
  - 2.2.5
  - 2.1.10

env:
  global:
  - PYCALL_DEBUG_FIND_LIBPYTHON=1
  matrix:
  - PYTHON=python
  - PYTHON=python3 LIBPYTHON=wrong_value
  - LIBPYTHON=/opt/python/3.5.3/lib/libpython3.5m.so

addons:
  apt:
    packages:
      - python3
      - python3-dev
      - python3-all
      - python3-all-dev

before_install:
  - gem update --system
  - gem update bundler

before_script:
  - bundle exec rake clobber compile
  - echo === python investigator.py ===
  - python lib/pycall/python/investigator.py
  - python3 lib/pycall/python/investigator.py
  - pip install numpy
  - pip3 install numpy

matrix:
  allow_failures:
  - env: PYTHON=python  # Ignore failed on python 2.7
